### ISSUE TITLE
BCVのVersion 1.3.0において、Win7 32ビットにて動作しない。(In version 1.3.0 of BCV, it  don't work with win7_32bit)

### ISSUE THREAD

**Issue by sahya** [HIJIKIsw/Mixer-Comment-Viewer#1]
# Target Version
Windows7 32bit

# Defect OS
Windows7 32bit

# Defect Detail
Win7 32ビットでBCVを起動させたところ、  
「#Error 14 -->内部エラーが発生しました。(14)」と表示されます。  
ログなどを表示させようとしたところ、ありませんでしたので  
スクリーンショットを張ります。
![エラー発生時のスクリーンショット1](https://pbs.twimg.com/media/DArQSBDXgAE-I6H.jpg:small "エラー発生時のスクリーンショット1")

------------------------------------
その後、HIJIKIswさんにご連絡をした後、BCVを直接起動する、batfileを提供いただきましたが、動作しませんでした。
![エラー発生時のスクリーンショット2](https://pbs.twimg.com/media/DAxYOSIUwAAiZbt.jpg:small  "エラー発生時のスクリーンショット2")

# Request
お手数ですが、修正をお願いします。

**Comment by sahya** [comment]
HIJIKIswさんより以下のコメントをいただいております。

-----

#BeamCommentViewer について「32bit OS 上で動作しない」という報告をいただいております。6 月中旬頃には、32bit OS に向けた対応、Beam サービス名称変更に伴うアプリ名称の変更などを含むアップデートを予定しております。もうしばらくお待ち下さい。

**Comment by HIJIKIsw** [comment]
1.4.0 にて対応しました。ご報告ありがとうございました。
