### ISSUE TITLE
beam.proのサービス名変更対応のお願い (Please correct BCV  Along with the change in the service name of beam.pro.)

### ISSUE THREAD

**Issue by sahya** [HIJIKIsw/Mixer-Comment-Viewer#2]
Beam　のサービス名がMixerになりました。
コメントビューアーの名前変更をしたほうが良いと思います。

#### メモ
------
- コメントビューアーの名前変更
- アイコンの変更
- 内部処理の変更

**Comment by sahya** [comment]
HIJIKIswさんより以下のコメントをいただいております。

-----

Beam.pro  サービス名変更に伴い、#BeamCommentViewer の新しい名称、新しいアプリアイコンおよびロゴ画像を募集します。申し訳ありませんが謝礼はお支払できません。お暇な方や物好きな方がいましたらよろしくお願いいたします。

6 月中旬頃には、32bit OS に向けた対応、Beam サービス名称変更に伴うアプリ名称の変更などを含むアップデートを予定しております。もうしばらくお待ち下さい。

**Comment by HIJIKIsw** [comment]
1.4.0 にて対応しました。ご報告ありがとうございました。
